import Drawer from "@/components/ui/drawer";
import CartModal from "@/features/cart/CartModal";
import HomeView from "@/views/home";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <Head>
        <title>BShopp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full h-full">
        <HomeView />
      </main>
    </>
  );
}
