import HomeView from "@/views/home";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>BShopp</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="w-full h-full">
        <HomeView />
      </main>
    </>
  );
}
